// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/kratos-multi-repo/app-layout/internal/biz/greeter"
	"github.com/kratos-multi-repo/app-layout/internal/conf"
	"github.com/kratos-multi-repo/app-layout/internal/data"
	"github.com/kratos-multi-repo/app-layout/internal/server"
	"github.com/kratos-multi-repo/app-layout/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client, cleanup, err := data.NewClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	iRepo := data.NewGreeterRepo(client, logger)
	iUseCase := greeter.NewUseCase(iRepo, logger)
	greeterService := service.NewGreeterService(iUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
